name: tests

on:
  push:
      branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Install front-end dependencies
        run: |
          npm install
          npm run build

      - name: Prepare Laravel Application
        run: |
          php -r "file_exists('.env') || copy('.env.ci', '.env');"
          php artisan key:generate

      - name: Run Testsuite
        run: vendor/bin/phpunit
